version: "3.3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana

  pgadmin_service:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - my-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postgres_service:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Paris
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - my-network
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres_service
    networks:
      - my-network
    volumes:
      - keycloak_data:/opt/keycloak/data  
          

networks:
  my-network:
    driver: bridge

volumes:
  grafana-data:
  grafana-conf: 
  pgadmin-data: 
  postgres-data: 
  keycloak_data: 